# Generated by Django 3.0.6 on 2020-05-16 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(default=uuid.UUID('8c884237-83a9-457f-bd8e-fb48ca537563'), editable=False, max_length=10, unique=True)),
                ('story', models.TextField()),
            ],
        ),
    ]
