# Generated by Django 3.0.6 on 2020-05-16 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesan',
            name='secret',
            field=models.CharField(default=uuid.UUID('f0d25946-7f6b-468c-8595-278dfd3d0f88'), editable=False, max_length=10, unique=True),
        ),
    ]
