# Generated by Django 3.0.6 on 2020-05-16 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200516_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesan',
            name='secret',
            field=models.CharField(default=uuid.UUID('ec6e574e-315b-4e55-9314-03ae0f78b558'), editable=False, max_length=10, unique=True),
        ),
    ]
