# Generated by Django 3.0.6 on 2020-05-16 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200516_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesan',
            name='secret',
            field=models.CharField(default=uuid.UUID('2015e1b0-fe97-46ff-b55e-c53cba08fe2f'), max_length=10, unique=True),
        ),
    ]
