# Generated by Django 3.0.6 on 2020-05-16 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200516_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='nama',
            field=models.TextField(default="Nama'\x08"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pesan',
            name='secret',
            field=models.CharField(default=uuid.UUID('d2bc0187-bec9-4846-96f0-c69c8a8ae974'), max_length=10, unique=True),
        ),
    ]
