# Generated by Django 3.0.6 on 2020-05-16 11:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200516_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='img',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pesan',
            name='secret',
            field=models.CharField(default=uuid.UUID('2c58c560-1647-4763-a245-caaa2e1c0fc3'), max_length=36, unique=True),
        ),
    ]
