# Generated by Django 3.0.6 on 2020-05-16 11:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200516_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesan',
            name='secret',
            field=models.CharField(default=uuid.UUID('4ef69656-f878-4d43-b1b0-65c8d5ae493b'), max_length=36, unique=True),
        ),
    ]
