# Generated by Django 2.2.7 on 2020-05-16 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200516_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesan',
            name='secret',
            field=models.CharField(default=uuid.UUID('b82a147c-e923-400d-bfc8-eda7c23415d6'), max_length=36, unique=True),
        ),
    ]
