# Generated by Django 2.2.7 on 2020-05-16 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200516_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesan',
            name='secret',
            field=models.CharField(default=uuid.UUID('37520d74-a65e-4c48-baaa-6ec05375058a'), max_length=36, unique=True),
        ),
    ]
