# Generated by Django 2.2.7 on 2020-05-18 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200516_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesan',
            name='secret',
            field=models.CharField(default=uuid.UUID('bfc387d9-6f80-4f80-affb-f17c2f596d68'), max_length=36, unique=True),
        ),
    ]
